<?php

namespace App\Models;

use App\Scopes\RvsScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use HasFactory;
    protected $guarded=[];
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function post()
    {
        return $this->belongsTo(Comment::class);
    }

    public static function boot()
    {
        static::addGlobalScope(new RvsScope());
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
