<?php

namespace App\Models;

use App\Scopes\RvsScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $fillable=['body','image'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    protected static function boot()
    {
        static::addGlobalScope(new RvsScope());
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function getDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function likes()
    {
        return $this->belongsToMany(User::class,"likes","post_id",'user_id');
    }

    public function likestatus()
    {
        return $this->likes()->get()->contains(auth()->user());
    }
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}
